task_type: keypoint_detection
dataset_category: cocokpts
calibration_dataset: cocokpts
input_dataset: cocokpts
postprocess:
  detection_threshold: 0.3
  save_output: false
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
  logits_bbox_to_bbox_ls: false
preprocess:
  resize: 640
  crop: 640
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: null
  resize_with_pad: true
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_scale:
  - 0.003922
  - 0.003922
  - 0.003922
  runtime_options:
    tensor_bits: 16
    accuracy_level: 1
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 1
    advanced_options:calibration_iterations: 1
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    info:
      prequantized_model_type: 0
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: yolov5s6_pose_640_ti_lite_metaarch.prototxt
  model_path: yolov5s6_pose_640_ti_lite_54p9_82p2.onnx
  model_id: kd-7040
  input_details: null
  output_details: null
  num_inputs: 1
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 54.9
  model_shortlist: null
